name: test

on:
  push:
    branches: [ "tests-back-login" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: go test -v ./...

  notify-on-failure:
    needs: test
    runs-on: ubuntu-latest
    if: always() && ${{ needs.test.result != 'success' }}
    steps:
      - name: Notify on Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Build or test failed! Check the workflow logs for details."}' $DISCORD_WEBHOOK_URL
